# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 936d25d94ba3721c79acf9e47efad88e6ab17de088c5d9d3146f92dbe75157fdbbb4c8622bfb054ce16d4aeb22a94efd85544323857cb219544a9363558a91e5

test:
  secret_key_base: c1911d496711ef6643c54264e6c25ff8bbc5733cf6cf52a94c682edd2ce69b9fa08f65c718f21696b7ca2944206065c559bf0113d6d3c58a4c674fd3a9a32fa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
